Contact.create!([
  {first_name: "Cyndy", last_name: "Kertzmann", email: "kertzmann.cyndy@yahoo.com", phone_number: "901-924-4565", middle_name: nil, bio: nil},
  {first_name: "Michael", last_name: "Carter", email: "carter.michael@yahoo.com", phone_number: "988-822-3919 x12799", middle_name: nil, bio: nil},
  {first_name: "Edwin", last_name: "Schowalter", email: "schowalter.edwin@hotmail.com", phone_number: "(936) 872-3548", middle_name: nil, bio: nil},
  {first_name: "Colette", last_name: "Cummerata", email: "cummerata.colette@gmail.com", phone_number: "548.350.5170", middle_name: nil, bio: nil},
  {first_name: "Keneth", last_name: "Pollich", email: "pollich_keneth@gmail.com", phone_number: "456.552.6795 x48446", middle_name: nil, bio: nil},
  {first_name: "Chas", last_name: "Harvey", email: "harvey.chas@yahoo.com", phone_number: "1-848-929-5586 x42665", middle_name: nil, bio: nil},
  {first_name: "Arnoldo", last_name: "Erdman", email: "arnoldo_erdman@gmail.com", phone_number: "299-675-5686", middle_name: nil, bio: nil},
  {first_name: "Leticia", last_name: "Schneider", email: "schneider.leticia@hotmail.com", phone_number: "972.101.0428", middle_name: nil, bio: nil},
  {first_name: "Trent", last_name: "Simonis", email: "trent_simonis@hotmail.com", phone_number: "(700) 504-2115 x98209", middle_name: nil, bio: nil},
  {first_name: "Bernetta", last_name: "Marks", email: "marks_bernetta@gmail.com", phone_number: "607-907-6010", middle_name: nil, bio: nil},
  {first_name: "Rosaline", last_name: "Will", email: "will.rosaline@hotmail.com", phone_number: "1-436-363-4863", middle_name: nil, bio: nil},
  {first_name: "Edmund", last_name: "Spencer", email: "spencer_edmund@yahoo.com", phone_number: "(239) 745-7372", middle_name: nil, bio: nil},
  {first_name: "Ivey", last_name: "Heller", email: "heller.ivey@gmail.com", phone_number: "261-572-6213 x3286", middle_name: nil, bio: nil},
  {first_name: "Les", last_name: "Hodkiewicz", email: "hodkiewicz_les@yahoo.com", phone_number: "110.968.6488 x50218", middle_name: nil, bio: nil},
  {first_name: "Deshawn", last_name: "Kilback", email: "deshawn_kilback@hotmail.com", phone_number: "426-813-5856 x377", middle_name: nil, bio: nil},
  {first_name: "Winifred", last_name: "Pollich", email: "pollich.winifred@hotmail.com", phone_number: "601.949.5091", middle_name: nil, bio: nil},
  {first_name: "Perry", last_name: "Schaefer", email: "perry_schaefer@yahoo.com", phone_number: "1-290-016-8295 x061", middle_name: nil, bio: nil},
  {first_name: "Arminda", last_name: "Nikolaus", email: "nikolaus.arminda@gmail.com", phone_number: "994.766.3217 x351", middle_name: nil, bio: nil},
  {first_name: "Marlen", last_name: "Kshlerin", email: "marlen_kshlerin@yahoo.com", phone_number: "436.328.8836 x8879", middle_name: nil, bio: nil},
  {first_name: "Kaleigh", last_name: "Donnelly", email: "donnelly.kaleigh@yahoo.com", phone_number: "347.077.9161", middle_name: nil, bio: nil},
  {first_name: "Darcie", last_name: "Parker", email: "darcie.parker@gmail.com", phone_number: "1-323-873-5457 x17506", middle_name: nil, bio: nil},
  {first_name: "Kathryn", last_name: "O'Keefe", email: "kathryn_keefe_o@hotmail.com", phone_number: "891.846.4759", middle_name: nil, bio: nil},
  {first_name: "Donn", last_name: "Kerluke", email: "kerluke_donn@yahoo.com", phone_number: "544.211.4570 x366", middle_name: nil, bio: nil},
  {first_name: "Keesha", last_name: "Mueller", email: "mueller_keesha@yahoo.com", phone_number: "303.695.0351", middle_name: nil, bio: nil},
  {first_name: "Dino", last_name: "Jones", email: "dino_jones@gmail.com", phone_number: "1-619-812-4021 x5183", middle_name: nil, bio: nil},
  {first_name: "Lakeesha", last_name: "Marvin", email: "marvin_lakeesha@yahoo.com", phone_number: "830-324-4420", middle_name: nil, bio: nil},
  {first_name: "Tim", last_name: "Hammes", email: "hammes.tim@hotmail.com", phone_number: "679.291.9336 x428", middle_name: nil, bio: nil},
  {first_name: "James", last_name: "Fay", email: "james.fay@yahoo.com", phone_number: "(746) 324-0003 x674", middle_name: nil, bio: nil},
  {first_name: "Tyree", last_name: "Klocko", email: "klocko.tyree@gmail.com", phone_number: "408.779.7470 x86009", middle_name: nil, bio: nil},
  {first_name: "Rayna", last_name: "Skiles", email: "skiles.rayna@hotmail.com", phone_number: "827-101-6344", middle_name: nil, bio: nil},
  {first_name: "Joannie", last_name: "Davis", email: "joannie_davis@hotmail.com", phone_number: "1-837-696-4663", middle_name: nil, bio: nil},
  {first_name: "Candice", last_name: "Tremblay", email: "tremblay.candice@gmail.com", phone_number: "996-549-2671 x082", middle_name: nil, bio: nil},
  {first_name: "Lilia", last_name: "Paucek", email: "lilia_paucek@yahoo.com", phone_number: "295-254-4756", middle_name: nil, bio: nil},
  {first_name: "Travis", last_name: "McKenzie", email: "mckenzie_travis@yahoo.com", phone_number: "932-458-8883 x7755", middle_name: nil, bio: nil},
  {first_name: "Maryjane", last_name: "Hills", email: "maryjane_hills@hotmail.com", phone_number: "(845) 564-8973", middle_name: nil, bio: nil},
  {first_name: "Elwanda", last_name: "Heller", email: "elwanda_heller@hotmail.com", phone_number: "(484) 295-9362 x425", middle_name: nil, bio: nil},
  {first_name: "May", last_name: "Emard", email: "may_emard@yahoo.com", phone_number: "1-955-054-0309 x99092", middle_name: nil, bio: nil},
  {first_name: "Leontine", last_name: "Flatley", email: "leontine_flatley@gmail.com", phone_number: "939-964-6779 x96063", middle_name: nil, bio: nil},
  {first_name: "Troy", last_name: "Kiehn", email: "kiehn_troy@gmail.com", phone_number: "733-834-4646 x08844", middle_name: nil, bio: nil},
  {first_name: "Hilde", last_name: "Ruecker", email: "hilde_ruecker@hotmail.com", phone_number: "(748) 096-2794", middle_name: nil, bio: nil},
  {first_name: "Dewey", last_name: "Paucek", email: "dewey_paucek@hotmail.com", phone_number: "1-539-109-4560 x926", middle_name: nil, bio: nil},
  {first_name: "Ricky", last_name: "Schneider", email: "ricky_schneider@gmail.com", phone_number: "830.659.2590", middle_name: nil, bio: nil},
  {first_name: "Gertie", last_name: "Schmidt", email: "schmidt.gertie@gmail.com", phone_number: "1-961-790-6057 x78632", middle_name: nil, bio: nil},
  {first_name: "Elke", last_name: "Morar", email: "morar.elke@hotmail.com", phone_number: "(156) 277-6479 x267", middle_name: nil, bio: nil},
  {first_name: "Donya", last_name: "Mraz", email: "donya_mraz@hotmail.com", phone_number: "210-034-9856", middle_name: nil, bio: nil},
  {first_name: "Patsy", last_name: "Bashirian", email: "patsy.bashirian@gmail.com", phone_number: "285-279-8945 x896", middle_name: nil, bio: nil},
  {first_name: "Anamaria", last_name: "Casper", email: "anamaria_casper@gmail.com", phone_number: "(273) 666-5183", middle_name: nil, bio: nil},
  {first_name: "Armand", last_name: "Bartoletti", email: "bartoletti_armand@gmail.com", phone_number: "874-980-7973", middle_name: nil, bio: nil},
  {first_name: "Ike", last_name: "Marvin", email: "ike.marvin@hotmail.com", phone_number: "973-697-7492 x0765", middle_name: nil, bio: nil},
  {first_name: "Pedro", last_name: "Borer", email: "pedro_borer@yahoo.com", phone_number: "(676) 773-3214 x361", middle_name: nil, bio: nil},
  {first_name: "Russell", last_name: "Grant", email: "grant.russell@yahoo.com", phone_number: "666-497-6947 x10116", middle_name: nil, bio: nil},
  {first_name: "Ursula", last_name: "Romaguera", email: "romaguera_ursula@yahoo.com", phone_number: "(543) 133-4346", middle_name: nil, bio: nil},
  {first_name: "Elayne", last_name: "Beahan", email: "beahan_elayne@yahoo.com", phone_number: "(726) 042-6155 x808", middle_name: nil, bio: nil},
  {first_name: "Davis", last_name: "Gleichner", email: "davis.gleichner@hotmail.com", phone_number: "904.433.0998", middle_name: nil, bio: nil},
  {first_name: "Carly", last_name: "Farrell", email: "farrell.carly@yahoo.com", phone_number: "(949) 504-1636 x905", middle_name: nil, bio: nil},
  {first_name: "Shonda", last_name: "Hahn", email: "shonda_hahn@yahoo.com", phone_number: "(453) 447-7868 x484", middle_name: nil, bio: nil},
  {first_name: "Tammie", last_name: "Morar", email: "morar.tammie@yahoo.com", phone_number: "529-573-8515 x04812", middle_name: nil, bio: nil},
  {first_name: "Rebecca", last_name: "Dooley", email: "dooley_rebecca@gmail.com", phone_number: "(910) 134-0492", middle_name: nil, bio: nil},
  {first_name: "Ambrose", last_name: "Bergstrom", email: "ambrose.bergstrom@yahoo.com", phone_number: "(394) 821-3605", middle_name: nil, bio: nil},
  {first_name: "Federico", last_name: "Pfannerstill", email: "federico.pfannerstill@yahoo.com", phone_number: "905-153-5129 x14923", middle_name: nil, bio: nil},
  {first_name: "Casandra", last_name: "Sanford", email: "sanford_casandra@yahoo.com", phone_number: "1-119-220-2507", middle_name: nil, bio: nil},
  {first_name: "Melvin", last_name: "Price", email: "melvin_price@hotmail.com", phone_number: "1-933-719-0103 x454", middle_name: nil, bio: nil},
  {first_name: "Carmelo", last_name: "Little", email: "little.carmelo@gmail.com", phone_number: "327-042-3934", middle_name: nil, bio: nil},
  {first_name: "Rolando", last_name: "Ratke", email: "rolando_ratke@yahoo.com", phone_number: "520.122.0776 x8307", middle_name: nil, bio: nil},
  {first_name: "Adeline", last_name: "Marquardt", email: "marquardt_adeline@gmail.com", phone_number: "406.071.8557 x1048", middle_name: nil, bio: nil},
  {first_name: "Sarai", last_name: "Will", email: "will_sarai@hotmail.com", phone_number: "409.631.9967", middle_name: nil, bio: nil},
  {first_name: "Candis", last_name: "Haley", email: "haley.candis@gmail.com", phone_number: "(909) 693-0701", middle_name: nil, bio: nil},
  {first_name: "Alphonse", last_name: "Shields", email: "shields_alphonse@yahoo.com", phone_number: "(355) 765-5292", middle_name: nil, bio: nil},
  {first_name: "Rigoberto", last_name: "Mueller", email: "mueller.rigoberto@hotmail.com", phone_number: "(614) 544-9603 x3522", middle_name: nil, bio: nil},
  {first_name: "Eboni", last_name: "Mertz", email: "mertz_eboni@hotmail.com", phone_number: "808.854.9448 x6055", middle_name: nil, bio: nil},
  {first_name: "Trevor", last_name: "Stehr", email: "stehr.trevor@yahoo.com", phone_number: "1-155-686-0309 x209", middle_name: nil, bio: nil},
  {first_name: "Earnestine", last_name: "Lehner", email: "earnestine.lehner@gmail.com", phone_number: "932.950.9534", middle_name: nil, bio: nil},
  {first_name: "Kenya", last_name: "Feil", email: "feil_kenya@gmail.com", phone_number: "348-058-6994 x5532", middle_name: nil, bio: nil},
  {first_name: "Catarina", last_name: "Little", email: "catarina.little@gmail.com", phone_number: "1-234-966-2179 x543", middle_name: nil, bio: nil},
  {first_name: "Stepanie", last_name: "Gerhold", email: "stepanie_gerhold@hotmail.com", phone_number: "824-680-0128 x547", middle_name: nil, bio: nil},
  {first_name: "Liliana", last_name: "Fritsch", email: "liliana_fritsch@gmail.com", phone_number: "(302) 786-1785 x8379", middle_name: nil, bio: nil},
  {first_name: "Dominique", last_name: "Heller", email: "heller.dominique@yahoo.com", phone_number: "367-337-5628 x58503", middle_name: nil, bio: nil},
  {first_name: "Ismael", last_name: "Rowe", email: "rowe.ismael@hotmail.com", phone_number: "905-492-8427 x55582", middle_name: nil, bio: nil},
  {first_name: "Jessie", last_name: "Sawayn", email: "sawayn_jessie@hotmail.com", phone_number: "750-480-0288 x6194", middle_name: nil, bio: nil},
  {first_name: "Isaac", last_name: "Ondricka", email: "isaac_ondricka@hotmail.com", phone_number: "243.001.1156 x477", middle_name: nil, bio: nil},
  {first_name: "Lucy", last_name: "Kuhic", email: "kuhic.lucy@hotmail.com", phone_number: "754.679.1560 x854", middle_name: nil, bio: nil},
  {first_name: "Clinton", last_name: "Nitzsche", email: "clinton_nitzsche@hotmail.com", phone_number: "1-683-443-8571 x21274", middle_name: nil, bio: nil},
  {first_name: "Dorcas", last_name: "Mraz", email: "dorcas_mraz@yahoo.com", phone_number: "946.789.3129 x3847", middle_name: nil, bio: nil},
  {first_name: "Davis", last_name: "Klocko", email: "davis.klocko@gmail.com", phone_number: "1-768-869-0835 x58306", middle_name: nil, bio: nil},
  {first_name: "Anika", last_name: "Balistreri", email: "anika.balistreri@yahoo.com", phone_number: "1-562-375-6753 x934", middle_name: nil, bio: nil},
  {first_name: "Marlin", last_name: "Pacocha", email: "marlin_pacocha@gmail.com", phone_number: "1-653-245-1211 x96610", middle_name: nil, bio: nil},
  {first_name: "Karole", last_name: "Maggio", email: "karole.maggio@hotmail.com", phone_number: "1-577-490-1806", middle_name: nil, bio: nil},
  {first_name: "Bradley", last_name: "Stokes", email: "bradley.stokes@yahoo.com", phone_number: "760.755.2341 x836", middle_name: nil, bio: nil},
  {first_name: "Myung", last_name: "Mraz", email: "myung_mraz@yahoo.com", phone_number: "(218) 720-5050 x61966", middle_name: nil, bio: nil},
  {first_name: "Matthew", last_name: "Anderson", email: "anderson.matthew@yahoo.com", phone_number: "(358) 658-6081", middle_name: nil, bio: nil},
  {first_name: "Wiley", last_name: "O'Reilly", email: "wiley_reilly_o@hotmail.com", phone_number: "140.001.5849", middle_name: nil, bio: nil},
  {first_name: "Dan", last_name: "Goodwin", email: "dan_goodwin@hotmail.com", phone_number: "621.469.7249", middle_name: nil, bio: nil},
  {first_name: "Marco", last_name: "Adams", email: "marco.adams@hotmail.com", phone_number: "933.827.3572", middle_name: nil, bio: nil},
  {first_name: "Henrietta", last_name: "Hane", email: "hane.henrietta@yahoo.com", phone_number: "(643) 976-1342 x24969", middle_name: nil, bio: nil},
  {first_name: "Sylvie", last_name: "Collier", email: "collier_sylvie@yahoo.com", phone_number: "(223) 247-7578 x1659", middle_name: nil, bio: nil},
  {first_name: "Lyndon", last_name: "Lakin", email: "lakin_lyndon@hotmail.com", phone_number: "163.748.6648 x7161", middle_name: nil, bio: nil},
  {first_name: "Delphia", last_name: "Hammes", email: "delphia_hammes@gmail.com", phone_number: "757-279-2552 x1834", middle_name: nil, bio: nil},
  {first_name: "Suzi", last_name: "Veum", email: "suzi.veum@yahoo.com", phone_number: "1-574-661-7085 x444", middle_name: nil, bio: nil},
  {first_name: "Andres", last_name: "Reilly", email: "andres_reilly@hotmail.com", phone_number: "1-357-809-0137 x209", middle_name: nil, bio: nil},
  {first_name: "Renate", last_name: "Kohler", email: "kohler_renate@hotmail.com", phone_number: "348-321-0779 x93696", middle_name: nil, bio: nil},
  {first_name: "Mae", last_name: "Grant", email: "mae_grant@gmail.com", phone_number: "712-739-1524 x67809", middle_name: nil, bio: nil},
  {first_name: "Cecil", last_name: "Kuhic", email: "cecil_kuhic@hotmail.com", phone_number: "364-787-0791 x20709", middle_name: nil, bio: nil},
  {first_name: "Zachery", last_name: "Wyman", email: "zachery.wyman@hotmail.com", phone_number: "1-971-094-4780", middle_name: nil, bio: nil},
  {first_name: "Darline", last_name: "Rohan", email: "rohan_darline@hotmail.com", phone_number: "1-468-868-2574 x06263", middle_name: nil, bio: nil},
  {first_name: "Elijah", last_name: "Grady", email: "elijah.grady@yahoo.com", phone_number: "379.076.1056 x8111", middle_name: nil, bio: nil},
  {first_name: "Carlo", last_name: "Mante", email: "carlo_mante@gmail.com", phone_number: "595.662.5678 x0926", middle_name: nil, bio: nil},
  {first_name: "Tory", last_name: "Keebler", email: "tory_keebler@yahoo.com", phone_number: "1-576-657-1036", middle_name: nil, bio: nil},
  {first_name: "Tonisha", last_name: "Rodriguez", email: "tonisha_rodriguez@hotmail.com", phone_number: "313-041-8647 x176", middle_name: nil, bio: nil},
  {first_name: "Beverley", last_name: "Fisher", email: "beverley_fisher@hotmail.com", phone_number: "1-673-344-6691 x68860", middle_name: nil, bio: nil},
  {first_name: "Titus", last_name: "Runte", email: "runte_titus@yahoo.com", phone_number: "1-951-611-1857 x8239", middle_name: nil, bio: nil},
  {first_name: "Marni", last_name: "Schultz", email: "schultz_marni@yahoo.com", phone_number: "995.675.4397", middle_name: nil, bio: nil},
  {first_name: "Shelia", last_name: "Anderson", email: "shelia.anderson@hotmail.com", phone_number: "1-103-757-8382", middle_name: nil, bio: nil},
  {first_name: "Dana", last_name: "Kozey", email: "dana.kozey@yahoo.com", phone_number: "460.839.7292 x94860", middle_name: nil, bio: nil},
  {first_name: "Dana", last_name: "Champlin", email: "dana.champlin@gmail.com", phone_number: "542.135.8056 x9502", middle_name: nil, bio: nil},
  {first_name: "Ocie", last_name: "Olson", email: "olson_ocie@gmail.com", phone_number: "947.451.7953 x340", middle_name: nil, bio: nil},
  {first_name: "Latricia", last_name: "Lind", email: "latricia.lind@hotmail.com", phone_number: "413-311-3754", middle_name: nil, bio: nil},
  {first_name: "Lee", last_name: "Keeling", email: "lee.keeling@gmail.com", phone_number: "(994) 841-4984 x920", middle_name: nil, bio: nil},
  {first_name: "Harley", last_name: "Franecki", email: "franecki.harley@gmail.com", phone_number: "524.774.0303", middle_name: nil, bio: nil},
  {first_name: "Gregorio", last_name: "Cormier", email: "cormier.gregorio@gmail.com", phone_number: "1-965-428-8108 x207", middle_name: nil, bio: nil},
  {first_name: "Francisco", last_name: "Hirthe", email: "hirthe_francisco@hotmail.com", phone_number: "(144) 339-6805", middle_name: nil, bio: nil},
  {first_name: "Sharan", last_name: "Bradtke", email: "bradtke_sharan@hotmail.com", phone_number: "1-958-211-1588 x07309", middle_name: nil, bio: nil},
  {first_name: "Toccara", last_name: "Baumbach", email: "toccara_baumbach@yahoo.com", phone_number: "854-619-2741 x9312", middle_name: nil, bio: nil},
  {first_name: "Darrick", last_name: "Walter", email: "darrick_walter@gmail.com", phone_number: "667.314.0711 x900", middle_name: nil, bio: nil},
  {first_name: "Johnnie", last_name: "King", email: "king_johnnie@gmail.com", phone_number: "1-279-589-9196 x669", middle_name: nil, bio: nil},
  {first_name: "Elliott", last_name: "Tillman", email: "elliott.tillman@yahoo.com", phone_number: "835.642.1094 x691", middle_name: nil, bio: nil},
  {first_name: "Norberto", last_name: "Hoppe", email: "norberto.hoppe@gmail.com", phone_number: "(835) 261-6973 x6244", middle_name: nil, bio: nil},
  {first_name: "Buddy", last_name: "Kautzer", email: "kautzer.buddy@hotmail.com", phone_number: "178.974.0193", middle_name: nil, bio: nil},
  {first_name: "Francisco", last_name: "Schiller", email: "schiller.francisco@gmail.com", phone_number: "1-561-918-9478 x9023", middle_name: nil, bio: nil},
  {first_name: "Armand", last_name: "Kessler", email: "armand_kessler@hotmail.com", phone_number: "(110) 786-7991", middle_name: nil, bio: nil},
  {first_name: "Mathilda", last_name: "Shields", email: "mathilda.shields@hotmail.com", phone_number: "(673) 303-0544 x8955", middle_name: nil, bio: nil},
  {first_name: "Rudolph", last_name: "Padberg", email: "padberg_rudolph@gmail.com", phone_number: "526.493.8636 x3639", middle_name: nil, bio: nil},
  {first_name: "Signe", last_name: "Lowe", email: "lowe.signe@gmail.com", phone_number: "432-670-6187 x399", middle_name: nil, bio: nil},
  {first_name: "Lon", last_name: "Kub", email: "kub.lon@gmail.com", phone_number: "412.446.3783 x22715", middle_name: nil, bio: nil},
  {first_name: "Emmett", last_name: "Kerluke", email: "kerluke.emmett@yahoo.com", phone_number: "351-831-6664", middle_name: nil, bio: nil},
  {first_name: "Dana", last_name: "Renner", email: "dana_renner@yahoo.com", phone_number: "208.222.0457", middle_name: nil, bio: nil},
  {first_name: "Lowell", last_name: "Hettinger", email: "hettinger.lowell@gmail.com", phone_number: "(462) 907-4312", middle_name: nil, bio: nil},
  {first_name: "Terence", last_name: "Krajcik", email: "terence_krajcik@hotmail.com", phone_number: "(958) 295-2926", middle_name: nil, bio: nil},
  {first_name: "Leonia", last_name: "Gleason", email: "leonia.gleason@yahoo.com", phone_number: "(881) 278-9534 x75421", middle_name: nil, bio: nil},
  {first_name: "Justin", last_name: "Ruecker", email: "ruecker.justin@hotmail.com", phone_number: "(616) 202-1807", middle_name: nil, bio: nil},
  {first_name: "Melina", last_name: "Paucek", email: "melina.paucek@yahoo.com", phone_number: "408.335.7957 x3511", middle_name: nil, bio: nil},
  {first_name: "Teodoro", last_name: "Jones", email: "jones.teodoro@hotmail.com", phone_number: "286.437.5497 x0436", middle_name: nil, bio: nil},
  {first_name: "Truman", last_name: "Weimann", email: "truman_weimann@hotmail.com", phone_number: "552.071.0631", middle_name: nil, bio: nil},
  {first_name: "Franklyn", last_name: "Upton", email: "franklyn_upton@yahoo.com", phone_number: "(609) 524-8791 x7182", middle_name: nil, bio: nil},
  {first_name: "Tracy", last_name: "Reilly", email: "reilly_tracy@gmail.com", phone_number: "466-837-0426 x405", middle_name: nil, bio: nil},
  {first_name: "Keli", last_name: "Homenick", email: "homenick.keli@gmail.com", phone_number: "674-860-0261 x711", middle_name: nil, bio: nil},
  {first_name: "Truman", last_name: "Stokes", email: "truman.stokes@yahoo.com", phone_number: "1-434-220-1773 x0331", middle_name: nil, bio: nil},
  {first_name: "Willian", last_name: "Cummings", email: "cummings.willian@yahoo.com", phone_number: "1-424-839-1073 x825", middle_name: nil, bio: nil},
  {first_name: "Leonor", last_name: "Denesik", email: "leonor.denesik@gmail.com", phone_number: "1-415-863-5745", middle_name: nil, bio: nil},
  {first_name: "Kraig", last_name: "Bogisich", email: "bogisich.kraig@hotmail.com", phone_number: "580-081-4435 x3910", middle_name: nil, bio: nil},
  {first_name: "Delmer", last_name: "Fisher", email: "fisher_delmer@yahoo.com", phone_number: "773.382.1249 x5727", middle_name: nil, bio: nil},
  {first_name: "Bobby", last_name: "McGee", email: "bobbysworld@foxkids.net", phone_number: "310-333-5555", middle_name: "Jay", bio: nil},
  {first_name: "Bobby", last_name: "McGee", email: "bobbysworld@foxkids.net", phone_number: "310-333-5555", middle_name: "Jay", bio: "Is it love or is it gas that's the question you must ask."}
])
